"""Regenerate scenario/fontMetrics.py from the house faces the exports name.

Dev-only (D124, D125). The deck fits every table to its box before PowerPoint
sees it, which means predicting text widths and line heights - and doing so
on a server that may have none of these fonts installed. So the metrics are
measured once, here, from the very files the deck embeds (scenario/fonts/,
written by tools/buildOfficeFonts.py), and committed as a plain table. Run
again whenever those files are rebuilt or the deck names a new face.

    python3 tools/buildFontMetrics.py
"""
import os
import pprint

from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(HERE, '..', 'cyrus_pmg', 'pmgService', 'scenario', 'fonts')
FACES = {
    ('GS Sans', False): 'GSSans-Regular.ttf',
    ('GS Sans', True): 'GSSans-Bold.ttf',
    ('GS Sans Light', False): 'GSSans-Light.ttf',
    ('GS Sans Condensed', False): 'GSSansCondensed-Regular.ttf',
    ('GS Sans Condensed', True): 'GSSansCondensed-Bold.ttf',
}
EXTRA = ' —–·£€¥’…−↑↓'
CHARS = ''.join(chr(c) for c in range(32, 127)) + EXTRA


def measure(path):
    font = TTFont(path)
    upm = font['head'].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font['hmtx']
    widths = {}
    for ch in CHARS:
        glyph = cmap.get(ord(ch))
        if glyph is not None:
            widths[ch] = int(round(hmtx[glyph][0] * 1000.0 / upm))
    os2, hhea = font['OS/2'], font['hhea']
    win = (os2.usWinAscent + os2.usWinDescent) / float(upm)
    typo = (hhea.ascent - hhea.descent + hhea.lineGap) / float(upm)
    return {'widths': widths, 'line': round(max(win, typo), 4)}


def main():
    table = {'{}|{}'.format(name, 'b' if bold else 'r'): measure(os.path.join(FONTS, file))
             for (name, bold), file in FACES.items()}
    out = os.path.join(HERE, '..', 'cyrus_pmg', 'pmgService', 'scenario', 'fontMetrics.py')
    with open(out, 'w', encoding='utf-8') as handle:
        handle.write('"""Advance widths (per 1000 em) and single-line heights (per em) for the\n'
                     'house faces the deck names, measured from the files it embeds (D125).\n\n'
                     'GENERATED by service/tools/buildFontMetrics.py - do not edit by hand.\n"""\n\n')
        handle.write('METRICS = ')
        handle.write(pprint.pformat(table, width=100, compact=True))
        handle.write('\n')
    print('wrote', os.path.normpath(out), {k: v['line'] for k, v in table.items()})


if __name__ == '__main__':
    main()
